PREFIX rdf: <http://wwww3org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://wwww3org/2000/01/rdf-schema#> 
PREFIX bf: <http://buildsys.org/ontologies/BrickFrame#>
PREFIX brick: <http://buildsys.org/ontologies/Brick#> 
PREFIX btag: <http://buildsys.org/ontologies/BrickTag#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX soda_hall: <http://buildsys.org/ontologies/building_example#> 

SELECT ?equipment ?room
WHERE {
    ?room rdf:type brick:Room .

    ?equipment bf:isLocatedIn ?room .

    { ?equipment rdf:type/rdfs:subClassOf* brick:Lighting_System .}
    UNION
    { ?equipment rdf:type/rdfs:subClassOf* brick:Heating_Ventilation_Air_Conditioning_System .}
}