PREFIX rdf: <http://wwww3org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://wwww3org/2000/01/rdf-schema#> 
PREFIX bf: <http://buildsys.org/ontologies/BrickFrame#>
PREFIX brick: <http://buildsys.org/ontologies/Brick#> 
PREFIX btag: <http://buildsys.org/ontologies/BrickTag#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX soda_hall: <http://buildsys.org/ontologies/building_example#> 

SELECT ?ahu ?sensor
WHERE {
    ?ahu rdf:type/rdfs:subClassOf* brick:AHU .
    ?ahu (bf:feeds|bf:hasPoint|bf:hasPart|bf:contains)* ?sensor .

    { ?sensor rdf:type/rdfs:subClassOf* brick:Reheat_Valve_Command }
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Cooling_Valve_Command }
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Mixed_Air_Temperature_Sensor }
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Outside_Air_Temperature_Sensor }
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Return_Air_Temperature_Sensor }
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Supply_Air_Temperature_Sensor }
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Outside_Air_Humidity_Sensor }
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Return_Air_Temperature_Sensor}
    UNION
    { ?sensor rdf:type/rdfs:subClassOf* brick:Outside_Air_Damper_Position_Sensor }
}